# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
  - 2.7
  - 3.4
# List the versions of Django you'd like to test against
env:
  - DJANGO_VERSION=1.8.3
# Tell it the things it will need to install when it boots
install:
   # Install the dependencies the app itself has
   # which in this case I choose to keep in a requirements file
 - pip install coveralls
 - pip install -r requirements/development.txt --use-mirrors
   # Install whatever version of Django that's listed above
   # Travis is currently working on
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
before_script:
 - python manage.py migrate
# Tell Travis how to run the test script itself
script: coverage run --source='.' manage.py test
after_success: coveralls
